kind: Namespace
apiVersion: v1
metadata:
  name: nsmysql
  labels:
    app: mysql            
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
  - image: 899518646067.dkr.ecr.us-east-1.amazonaws.com/webapp-dev-mysql:v1.0 
    name: mysql
    resources: {}
    ports:
      - name: mysql
        containerPort: 3306
        protocol: TCP
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "pw"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
