apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    resources: {}
    ports:
      - name: mysql
        containerPort: 3306
        protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
