apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: appReplicaSet
  namespace: nsapp
  labels:
    app: employees
    owner: rutuj
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: employees
      template:
        metadata:
          app: employees
        spec:
          containers:
          - name: employees
            image: 899518646067.dkr.ecr.us-east-1.amazonaws.com/webapp-dev-app:v1.0
            env:
            - name: DBHOST
              value: "10.96.143.131"
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: root
            - name: DBPWD
              value: pw
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          dnsPolicy: ClusterFirst 
